# Generated by Django 5.0.6 on 2024-08-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cartitem_user_cart_cartitem_cart'),
        ('store', '0003_alter_product_category_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='carts.CartItem', to='store.product'),
        ),
    ]
