# Generated by Django 5.0.6 on 2024-08-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
