# Generated by Django 5.0.6 on 2024-07-02 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('automobiles', 'Automobiles'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('food and beverages', 'Food and Beverages'), ('furnitures and decor', 'Furnitures and Decor'), ('mobile phones', 'Mobile Phones'), ('toys', 'Toys')], max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
    ]
